version: '3.7'

services:
  microchaos-1:
    image: microchaos
    environment:
      CONFIG_PATH: '/app/config/all-commands.yml'
    build:
      context: .
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./examples:/app/config
    deploy:
      resources:
        limits:
          memory: '50M'
    depends_on:
      - consul

  consul:
    image: consul:latest
    environment:
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: agent -server -data-dir=/consul/data -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0


  tests:
    image: microchaos
    build:
      context: .
      target: builder
    command: gradle test --no-daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock