#-------------------------------------------------------------
# Build

FROM gradle:6.3-jdk11 as builder

# Install curl
RUN apt-get update && apt-get install -y \
  curl net-tools \
  && rm -rf /var/lib/apt/lists/*

# Install docker client
ENV DOCKER_CHANNEL stable
ENV DOCKER_VERSION 19.03.8-ce
RUN curl -fsSL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" \
  | tar -xzC /usr/local/bin --strip=1 docker/docker

ENV GRADLE_HOME /usr/bin/gradle
ENV GRADLE_USER_HOME /cache

COPY build.gradle gradle.properties settings.gradle ./
# Trick to force Gradle to download dependencies and cache it
RUN mkdir -p src/main/java
RUN sh -c "echo 'public class Dummy {}' > src/main/java/Dummy.java && gradle -i compileJava"

COPY src/  ./src

# expose for testcontainers
VOLUME /var/run/docker.sock

CMD gradle test