{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.image }}
          ports:
            - containerPort: {{ .port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: "SERVICE_NAME"
              value: "{{ .name }}"
            - name: "CONSUL_URL"
              value: "{{ $.Values.consulLocation }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .name }}
  ports:
    - port: {{ $.Values.externalPort }}
      targetPort: {{ .port }}
---
{{- end }}
