apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
  namespace: {{ $.Values.namespace }}
spec:
  rules:
    - http:
        paths:
          {{- range $.Values.services }}
          - path: /{{ .name }}/*
            backend:
              serviceName: {{ .name }}
              servicePort: {{ $.Values.externalPort }}
          {{- end }}
